name: Publish to FlakeHub ️❄️
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*
 
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
 
jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      visibility: public

  CreateRelease:
    needs: DeterminateCI
    runs-on: ubuntu-latest
    # Only run this job when the workflow is triggered by a tag
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4
      - name: Release Notes ✍️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ github.ref_name }}"
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
          fi
          gh release create "${TAG}" --generate-notes --draft=false